[alias]
cleanup = [
    "clean",
    "-Z",
    "feature-unification"
]
xtask = "run --package xtask --bin xtask --"
tq = "test -- -q"
qt = "tq"
lint = "clippy --all-targets -- --cap-lints warn"
codegen = "run --package xtask --bin xtask -- codegen"
dist = "run --package xtask --bin xtask -- dist"

[build]
incremental = false
target-dir = "target"
rustc-wrapper = "sccache"
rustflags = [
    "-C",
    "linker=rust-lld",
    "-C",
    "link-arg=/OPT:NOREF",
    "-C",
    "link-arg=/INCREMENTAL:NO",
    "-C",
    "link-arg=/NODEFAULTLIB:libcmt",
    "-C",
    "target-cpu=native"
]

[env]
CARGO_WORKSPACE_DIR 	= { value = "", relative = true }
SCCACHE_CONF		= { value = "X:/EscamoteTheBeguiled/.config/sccache.toml", force = true }
